sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: eDdGB8FbaJLmhMAnWv5/WcNIVAU23foGdTSPuu/F5noEvzYlYlntMVqISHx0fvY5l7Spt+mrMMOSPx+fifscXve7Px3rnMjvTsClVyTIwLzggPwfBOs61kqBamzJ9mRDQ4lo6GEv868qAc5AlqhF2Qc1KYL0v2G/pUvlqw40WDexd3gF3c149DeZ0wASuS/BWqTLr6iVvkIdM/3mo8FU/fpdmeiIyQxuDEbjtHsdzw8eI6fMVU4eN8z6/J9UtjdUZ8vUA8VW7QNLsWAg9C2KhH0CXCi6Zhm2Z9F/J3GGPNSA6fFgIlFn3/d2DWJFurIIK16vY8tuEHfAlj5mJ9OUb9X+sAT64mWvMaCH1MxNaVzl00W+R8rLRuAfUkAkBCLnh7vz7AsUdt1TltIU4gRHt0o0yxsD3SCsVLGenzIReHBVvSea/AKcUakBBJale9Z4ILcH9caozMLfN41JmkqwDTkXUItIpRXZBqnddgtCKtrJGfdAR+zHlyScpoK9MqU2LVk9kzeb0kueKGX9Sl2gtb4G9T3bHlPG4GOfQ7oW80hHOHQEsf4T+2uHih+Vowt8AlnVtezGH1Rr+mr8Z+NFleNYof9H11GeO3xU8azztrLwINzPCrLELqj64DGmUSSW6smYLST17Y8Etui3h0CXEtXrjVW1vrYAwbB5TKoLNaA=
  - secure: IU2Ggo1CAU95iv5ZBiIXD4x0WCqk0x0Os1LvpQLoWN09IhXlv7uuZXhcymuWWoPpKcprZiz9CwqhBe7hF9sL9mmbnL+q+qYLlgD/9H3Zg0fdjJk5OraoC3D6blAnt9tPheaslX/+J/A2MbJIUEPtcIbaj8oZvr84VjYlh0Q8BsJOsmbklfmtcJM8FFhJF1W6vh5XLgzihzD8DeqndNx2pgktb4St28aGauiUPZCCQtHZWStBG7etmxPsd4ZRYzRMoyiv2K+Qn4ShOycgaCS/DhBeJFdBW6vfiZZQIzPjOT13bE3KP99nILqcWvTLBneSYrmk3I5ujdBa3YoVgJCKKikDwGR5o9wfGY3uHDaL48kIxWmIsnnvmJjUd3mvnMvQRGDP7rCJLwLBEklZ1XjIxmOWf4C2/TDQTAk54OkncDYbaRn0D88EyGhUzFozs+79e7bj07MLtoxMWhm34KossYNHYZFZ1Y9dzFi78uxnixigtgPqB698bSOTFh9BPzNxdm001wjziqrZLIPvWqHCs29Qsqsj9mRr3faaq3li4ziNeVFAr+QCqrg8H9BgR6Q/GN8J8BF2pWRk7Gcf6yf6UKGCyZhFk7MGQTA/0LTidB3ArCs2Vvwbpf/2MWqeSuK3qYXgJ88pD9q/lxvnmgbBiFGZOjZlM3oFlazUJ+trMOw=
  - secure: eBDf+n+Dmw01caLj1te4xoo41/4HVZqEXJgOz7HMpSkvUJE/R5I9oGuJIgqrIuucf5n171r8Omfz33h1H+IZL7Xz7qgC51M1CHQQVAvXpUNplYsvJ1c/TV9B7gJ70PaSKBiv6WdRC60WXOuTH62MF+rU5XVuiXLWIE3A/Aw85cVbbMGrzyo9vtW/8JfBP9BBDiBwZ9kN3wZNEPqhdX7gPJjMuvkcHPGsCvdTQRsrBaZTOlbRIeJvWk+4eTutGt/Ag0aBhIpno52np8k1AILhwkLn8zgt0t+JuqiNbEhaNfay1LYY4hPsBAdIhxhg1Wm441IJgNI0O07ZWc+BHpdIy4eiFXd97gjIwgq5FhcdwK3qqf7UtfXFC8hzIit9t0ubMbOksrGlJ/Nsjg5E+RY1/+8vrZ3s0RscRmoHd4qa4t+MJm/6KMYZ9dkit34cERZ6UX5fd7iqniaP9pXFtpCIzd2Uex90t1yS0YV/8UEXfDuACrmRw3uW0yLhmIzXmlLgY2e29j8mdrq3r4K07RIWm1/OBF6M70nhkmjgJeaKBMVgxB3F/jR8i7AJL3AnHUvqJ36cEq8y+n39tUkYKkvOl9CHnZ+uEViHLFFV0yyXTWD66ozICEgWvBw9vwo3l/50CGnzWTZDB2KTndQFfPmrIbqNWpico16TndRxOhs0oiI=
